# Generated by Django 3.2.6 on 2023-10-27 04:01

from django.db import migrations, models
import entry.models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='image',
            field=models.ImageField(blank=True, upload_to=entry.models.img_upload_func),
        ),
        migrations.AddField(
            model_name='symbol',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
