# Generated by Django 3.2.6 on 2023-10-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20231028_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='text',
            field=models.CharField(max_length=20),
        ),
    ]
