# Generated by Django 3.2.6 on 2023-10-29 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0005_alter_symbol_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to=settings.AUTH_USER_MODEL),
        ),
    ]
