name: SpeechBuddy Backend CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        script: |
          sh deploy.sh
